### ISSUE TITLE
Puppeteer Issue

### ISSUE THREAD

**Issue by gewondjan** [byuitechops/d2l-course-downloader#13]
I got this issue when running the course on this trello card: https://trello.com/c/aMptNZuX

Execution stops and the command is not returned to powershell.

```
Retrieving cookies...
Error: Evaluation failed: TypeError: Cannot read property 'innerHTML' of null
    at __puppeteer_evaluation_script__:1:106
    at ExecutionContext.evaluateHandle (C:\Users\jedimasterryan\repos\d2l-to-canvas-conversion-tool\node_modules\puppeteer\lib\ExecutionContext.js:124:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (C:\Users\jedimasterryan\repos\d2l-to-canvas-conversion-tool\node_modules\puppeteer\lib\helper.js:144:27)
    at ExecutionContext.evaluate (C:\Users\jedimasterryan\repos\d2l-to-canvas-conversion-tool\node_modules\puppeteer\lib\ExecutionContext.js:58:31)
    at ExecutionContext.<anonymous> (C:\Users\jedimasterryan\repos\d2l-to-canvas-conversion-tool\node_modules\puppeteer\lib\helper.js:145:23)
    at Frame.evaluate (C:\Users\jedimasterryan\repos\d2l-to-canvas-conversion-tool\node_modules\puppeteer\lib\FrameManager.js:439:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\jedimasterryan\repos\d2l-to-canvas-conversion-tool\node_modules\puppeteer\lib\helper.js:144:27)
    at Page.evaluate (C:\Users\jedimasterryan\repos\d2l-to-canvas-conversion-tool\node_modules\puppeteer\lib\Page.js:736:43)
    at Page.<anonymous> (C:\Users\jedimasterryan\repos\d2l-to-canvas-conversion-tool\node_modules\puppeteer\lib\helper.js:145:23)    at module.exports (C:\Users\jedimasterryan\repos\d2l-to-canvas-conversion-tool\node_modules\d2l-course-downloader\dlCourse.js:29:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
TypeError: Cannot read property 'fullAgenda' of undefined
    at Promise (C:\Users\jedimasterryan\repos\d2l-to-canvas-conversion-tool\main.js:7:28)
    at new Promise (<anonymous>)
    at module.exports (C:\Users\jedimasterryan\repos\d2l-to-canvas-conversion-tool\main.js:6:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by gewondjan** [comment]
After running the course again, the error did not come up, but the error continues to appear intermittently with future courses.  I have had it a total of 3 times as of this writing.
